### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kotahu** [Firew0lf/exppipes#20]
This mod need a license to properly let users know what rights to the source they have.
try https://choosealicense.com/ 

Thanks

**Comment by Ihamfp** [comment]
All Rights Reserved unless otherwise explicitly stated.

Check the Curseforge page for information about what you can do with the mod files.
For the code and assets... I will choose a more open license when I stop/slow down developing the mod (might be soon :tm: ). I will ask all the contributors when it happens, but for now the code they wrote is their, and the code I wrote is mine (do whatever you want with it, just don't claim as own or repost). I only do this to prevent repost/clones and to not have to send mails to way too much websites... Sorry for the inconvenience, and if you don't really like it, I don't either.

**Comment by kotahu** [comment]
Thank you for the clarification.
